services:
  mysql:
    image: mysql:latest
    container_name: golang_todo_mysql_v1
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_todo_v1:/var/lib/mysql

volumes:
  mysql_todo_v1: